import Providers from '@/redux/providers'
import '../globals.css'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
           <ToastContainer
            position="top-center"
            autoClose={3000}
          />
          {children}
        </Providers>
      </body>
    </html>
  )
}
