import Footer from '@/components/Footer/Footer'
import './globals.css';
import Header from '@/components/Header/Header'
import Providers from '@/redux/providers'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import UserInitializer from '@/components/UserInitializer/UserInitializer';

export const metadata = {
  title: 'RideNest',
  description: 'Generated by Next.js',
}

export default function MainLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <UserInitializer/>
          <Header />
          <ToastContainer
            position="top-center"
            autoClose={3000}
          />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
